# Generated by Django 4.2.3 on 2023-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('commentator_position', models.IntegerField(default=0)),
                ('stream_start', models.DateTimeField(auto_now_add=True)),
                ('game_offset', models.IntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Synchronization',
        ),
    ]
