# Generated by Django 4.2.3 on 2023-08-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_commentator_delete_synchronization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentator',
            name='commentator_position',
        ),
    ]
