# Generated by Django 4.2.3 on 2023-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_remove_commentator_commentator_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentator',
            name='stream_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='commentator',
            name='stream_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
