# Generated by Django 4.2.3 on 2023-08-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_commentator_stream_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentator',
            name='stream_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
