# Generated by Django 4.2.3 on 2023-08-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_alter_commentator_stream_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentator',
            name='playback_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
