# Generated by Django 4.2.3 on 2023-08-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentators', '0002_commentator_game_commentator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentator',
            name='commentator_name',
        ),
        migrations.RemoveField(
            model_name='commentator',
            name='event_name',
        ),
    ]
