# Generated by Django 4.2.3 on 2023-08-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
